FROM python:3.10-slim

WORKDIR /app

# Copy project (api + engine)
COPY . /app

# Install deps
RUN pip install --no-cache-dir -r konfluence_site/requirements.txt

# Expose
ENV PORT=8000
EXPOSE 8000

# Run API with Gunicorn
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "konfluence_site.api:app"]